[package]
name = "taskprinter"
version = "0.1.1"
edition = "2024"

[dependencies]
escpos = { version = "0.16.0", features = ["full"] }
escpos-rs = "0.4.3"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
